### PR TITLE
Fixing dates and exposing placeholders

### PR DESCRIPTION
**Pull request by 4rlekin**
I did both changes i mentioned - i really think that at least placeholders should be built in feature here.
Unfortunately i didn't manage to change template for adding placeholder to deal with it without putting braces around var - it may cause some issues for users (say with Django if somebody screw templates up). I think there is no other way, but if im wrong i'd really like to know how ;)

Thanks and enjoy

### CODE REVIEW

**Comment by niquola** [comment]
Why not just use `placeholder` property of fsSelect (i.e. fsPlaceholder => placeholder)?

**Comment by 4rlekin** [comment]
well, i wanted to mark that this is coming from the directive - im not especially attached to it to be honest

**Comment by niquola** [comment]
I think, `placeholder` is better remember-able and transparent. 
Another question: do you need dynamic binding for it or bind-once enough?

**Comment by 4rlekin** [comment]
Well, personally i just needed way to put my own text there, as i said, for purely i18n reasons. I can imagine somone wanting to dynamically changin placeholder, but i think it would be a bit of a stretch to forsee it in library. But then again i guess the same could be said about me wanting to have custom one.
What i wanted, and what i did, is simply to pull out 'placeholder' attribute to place where i would be able to set it to my liking

**Comment by niquola** [comment]
Ups, build is broken after pull
@4rlekin  could you try to fix specs?

**Comment by 4rlekin** [comment]
Sure, i will look into it tomorrow

**Pull request merged**
